server:
  port: 8080

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  datasource:
    url: jdbc:mysql://localhost:3306/othello
    username: admin
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver

#  CREATE TABLE tbl_users(
#  id	SERIAL PRIMARY KEY,
#  username VARCHAR,
#  password VARCHAR
#  );
#
#  CREATE TABLE tbl_difficults(
#  id	SERIAL PRIMARY KEY,
#  amount INTEGER,
#  user_id BIGINT REFERENCES tbl_users(id)
#  )